export enum Card {
  // Skills
  advance = <any> 'Advance',
  armorOfFaith = <any> 'Armor of Faith',
  blessedStrike = <any> 'Blessed Strike',
  challenge = <any> 'Challenge',
  cleansingTouch = <any> 'Cleansing Touch',
  defend = <any> 'Defend',
  defenseTraining = <any> 'Defense Training',
  divineFury = <any> 'Divine Fury',
  guard = <any> 'Guard',
  holyPower = <any> 'Holy Power',
  inspiration = <any> 'Inspiration',
  ironMace = <any> 'Iron Mace',
  oathOfHonor = <any> 'Oath of Honor',
  prayerOfHealing = <any> 'Prayer of Healing',
  prayerOfPeace = <any> 'Prayer of Peace',
  radiantLight = <any> 'Radiant Light',
  shieldSlam = <any> 'Shield Slam',
  stalwart = <any> 'Stalwart',
  timeOfNeed = <any> 'Time of Need',
  woodenShield = <any> 'Wooden Shield',

  // Items Act I
  chainmail = <any> 'Chainmail',
  crossbow = <any> 'Crossbow',
  elmGreatbow = <any> 'Elm Greatbow',
  heavyCloak = <any> 'Heavy Cloak',
  immolation = <any> 'Immolation',
  ironBattleaxe = <any> 'Iron Battleaxe',
  ironShield = <any> 'Iron Shield',
  ironSpear = <any> 'Iron Spear',
  leatherArmor = <any> 'Leather Armor',
  lightHammer = <any> 'Light Hammer',
  luckyCharm = <any> 'Lucky Charm',
  magicStaff = <any> 'Magic Staff',
  manaWeave = <any> 'Mana Weave',
  ringOfPower = <any> 'Ring of Power',
  scorpionHelm = <any> 'Scorpion Helm',
  sling = <any> 'Sling',
  steelBroadsword = <any> 'Steel Broadsword',
  sunburst = <any> 'Sunburst',

  // Items Act II
  demonhideLeather = <any> 'Demonhide Leather',
  dragontoothHammer = <any> 'Dragontooth Hammer',
  dwarvenFirebomb = <any> 'Dwarven Firebomb',
  elvenCloak = <any> 'Elven Cloak',
  grindingAxe = <any> 'Grinding Axe',
  heavySteelShield = <any> 'Heavy Steel Shield',
  iceStorm = <any> 'Ice Storm',
  ironBoundRing = <any> 'Iron-Bound Ring',
  latariLongbow = <any> 'Latari Longbow',
  lightningStrike = <any> 'Lightning Strike',
  maceOfKellos = <any> 'Mace of Kellos',
  platemail = <any> 'Platemail',
  steelGreatsword = <any> 'Steel Greatsword',
  tivalCrystal = <any> 'Tival Crystal'
}

export enum WornType {
  oneHand = <any> 'One Hand',
  twoHands = <any> 'Two Hands',
  armor = <any> 'Armor',
  other = <any> 'Other',
}
